name: Build taxonomies

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_taxonomies:
    name: Build taxonomies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install APT dependencies
        run: >
          sudo apt-get update

          sudo apt-get install -y --no-install-recommends
          cpanminus
          tesseract-ocr
          graphviz
          libtie-ixhash-perl
          libwww-perl
          libimage-magick-perl
          libxml-encoding-perl
          libtext-unaccent-perl
          libmime-lite-perl
          libcache-memcached-fast-perl
          libjson-pp-perl
          libclone-perl
          libcrypt-passwdmd5-perl
          libencode-detect-perl
          libgraphics-color-perl
          libbarcode-zbar-perl
          libxml-feedpp-perl
          liburi-find-perl
          libxml-simple-perl
          libexperimental-perl
          libapache2-request-perl
          libdigest-md5-perl
          libtime-local-perl
          libpq-dev
          libdbd-pg-perl
          libtemplate-perl
          liburi-escape-xs-perl
          libfile-copy-recursive-perl
          libemail-stuffer-perl
          liblist-moreutils-perl
          libexcel-writer-xlsx-perl
          libpod-simple-perl
          liblog-any-perl
          liblog-log4perl-perl
          liblog-any-adapter-log4perl-perl
          libemail-valid-perl
          libmath-fibonacci-perl
          libprobe-perl-perl
          libmath-round-perl
          libsoftware-license-perl
          libtest-differences-perl
          libtest-exception-perl
          libclass-accessor-lite-perl
          libclass-singleton-perl
          libfile-sharedir-install-perl
          libnet-idn-encode-perl
          libtest-nowarnings-perl
          libfile-chmod-perl
          libdata-dumper-concise-perl
          libdata-printer-perl
          libdata-validate-ip-perl
          libio-compress-perl
          libjson-maybexs-perl
          liblist-allutils-perl
          liblist-someutils-perl
          libdata-section-simple-perl
          libfile-which-perl
          libipc-run3-perl
          liblog-handler-perl
          libtest-deep-perl
          libwant-perl
          libfile-find-rule-perl
          liblinux-usermod-perl
          liblocale-maketext-lexicon-perl
          liblog-any-adapter-tap-perl
          libcrypt-random-source-perl
          libmath-random-isaac-perl
          libtest-sharedfork-perl
          libtest-warn-perl
          libsql-abstract-perl
          libauthen-sasl-saslprep-perl
          libauthen-scram-perl
          libbson-perl
          libclass-xsaccessor-perl
          libconfig-autoconf-perl
          libdigest-hmac-perl
          libpath-tiny-perl
          libsafe-isa-perl
          libspreadsheet-parseexcel-perl
          libtest-number-delta-perl

      - name: Install CPAN dependencies
        run: "sudo cpanm --notest --skip-satisfied --installdeps ."

      - name: Prepare dummy config
        run: |
          export BUILD_DIR=`pwd`
          ln -s ./lib/ProductOpener/Config_off.pm ./lib/ProductOpener/Config.pm
          cp ./lib/ProductOpener/Config2_sample.pm ./lib/ProductOpener/Config2.pm
          ln -s ./lib/ProductOpener/SiteLang_off.pm ./lib/ProductOpener/SiteLang.pm
          sed -i -e 's|\$server_domain = "openfoodfacts.org";|\$server_domain = "off.travis-ci.org";|g' ./lib/ProductOpener/Config2.pm
          sed -i -e 's|\/home\/off|'.'|g' ./lib/ProductOpener/Config2.pm

      - name: Build taxonomies
        run: "perl -CS -I$BUILD_DIR/lib ./scripts/build_tags_taxonomy.pl labels publish"
        env:
          PERL5LIB: "./lib"

      - name: Commit and create PR
        uses: EndBug/add-and-commit@v7.1.1
