name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  gulp:
    name: NPM Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v2.1.5
        with:
          node-version: "12.x"

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - run: npm ci

      - run: npm run build

  lint:
    name: NPM Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v2.1.5
        with:
          node-version: "12.x"

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - run: npm ci

      - run: npm run lint

  test:
    name: Perl testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50

      - uses: actions/setup-node@v2.1.5
        with:
          node-version: "12.x"

      - name: Find changed perl files
        uses: futuratrepadeira/changed-files@v3.3.0
        id: changed-perl
        with:
          repo-token: ${{ github.token }}
          pattern: '^(cgi|scripts)/.*\.pl$|^lib/ProductOpener/.*\.pm$'
          result-encoding: "string"

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - run: npm ci

      # Use APT packages from cpanfile
      - name: Install dependencies from APT
        run: >
          sudo apt-get update

          sudo apt-get install -y --no-install-recommends
          cpanminus
          tesseract-ocr
          graphviz
          libtie-ixhash-perl
          libwww-perl
          libimage-magick-perl
          libxml-encoding-perl
          libtext-unaccent-perl
          libmime-lite-perl
          libcache-memcached-fast-perl
          libjson-pp-perl
          libclone-perl
          libcrypt-passwdmd5-perl
          libencode-detect-perl
          libgraphics-color-perl
          libbarcode-zbar-perl
          libxml-feedpp-perl
          liburi-find-perl
          libxml-simple-perl
          libexperimental-perl
          libapache2-request-perl
          libdigest-md5-perl
          libtime-local-perl
          libpq-dev
          libdbd-pg-perl
          libtemplate-perl
          liburi-escape-xs-perl
          libfile-copy-recursive-perl
          libemail-stuffer-perl
          liblist-moreutils-perl
          libexcel-writer-xlsx-perl
          libpod-simple-perl
          liblog-any-perl
          liblog-log4perl-perl
          liblog-any-adapter-log4perl-perl
          libemail-valid-perl
          libmath-fibonacci-perl
          libprobe-perl-perl
          libmath-round-perl
          libsoftware-license-perl
          libtest-differences-perl
          libtest-exception-perl
          libclass-accessor-lite-perl
          libclass-singleton-perl
          libfile-sharedir-install-perl
          libnet-idn-encode-perl
          libtest-nowarnings-perl
          libfile-chmod-perl
          libdata-dumper-concise-perl
          libdata-printer-perl
          libdata-validate-ip-perl
          libio-compress-perl
          libjson-maybexs-perl
          liblist-allutils-perl
          liblist-someutils-perl
          libdata-section-simple-perl
          libfile-which-perl
          libipc-run3-perl
          liblog-handler-perl
          libtest-deep-perl
          libwant-perl
          libfile-find-rule-perl
          liblinux-usermod-perl
          liblocale-maketext-lexicon-perl
          liblog-any-adapter-tap-perl
          libcrypt-random-source-perl
          libmath-random-isaac-perl
          libtest-sharedfork-perl
          libtest-warn-perl
          libsql-abstract-perl
          libauthen-sasl-saslprep-perl
          libauthen-scram-perl
          libbson-perl
          libclass-xsaccessor-perl
          libconfig-autoconf-perl
          libdigest-hmac-perl
          libpath-tiny-perl
          libsafe-isa-perl
          libspreadsheet-parseexcel-perl
          libtest-number-delta-perl

          # 
          # Not available in Ubuntu 18.04 LTS
          # libmath-random-secure-perl
          # libgeoip2-perl
          # libmodule-build-pluggable-perl
          #

      - name: Cache perl modules
        uses: actions/cache@v2
        env:
          cache-name: cache-perl-modules
        with:
          path: ~/.cpanm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Setup perl and install dependencies
        run: |
          sudo cpanm --quiet --installdeps --notest --skip-satisfied .
          export BUILD_DIR=`pwd`
          ln -s $BUILD_DIR/lib/ProductOpener/Config_off.pm $BUILD_DIR/lib/ProductOpener/Config.pm
          cp $BUILD_DIR/lib/ProductOpener/Config2_sample.pm $BUILD_DIR/lib/ProductOpener/Config2.pm
          ln -s $BUILD_DIR/lib/ProductOpener/SiteLang_off.pm $BUILD_DIR/lib/ProductOpener/SiteLang.pm
          sed -i -e 's|\$server_domain = "openfoodfacts.org";|\$server_domain = "off.travis-ci.org";|g' $BUILD_DIR/lib/ProductOpener/Config2.pm
          sed -i -e 's|\/home\/off|'$BUILD_DIR'|g' $BUILD_DIR/lib/ProductOpener/Config2.pm

      - name: Check startup_apache2.pl
        run: "perl -c -CS -Ilib ./lib/startup_apache2.pl"

      - name: Check modified perl scripts
        run: >
          node ./scripts/check_perl.js
          ${{ steps.changed-perl.outputs.files_created }}
          ${{ steps.changed-perl.outputs.files_updated }}

      - name: Build language
        run: perl -CS -Ilib ./scripts/build_lang.pl

      - name: Rebuild taxonomies
        run: node ./scripts/refresh_taxonomies.js

      - name: Run unit tests
        run: "prove -l --jobs 2"
